bash ubuntu/ubuntu.sh
bash git/git.sh
bash curl/curl.sh
bash sshpass/sshpass.sh
bash openssh/openssh.sh
bash docker/docker.sh
bash docker-compose/docker-compose.sh
bash nodejs/nodejs.sh
bash pm2/pm2.sh
bash postgresql/postgresql.sh
bash visual_studio_code/visual_studio_code.sh
bash ansible/ansible.sh
